name: food_shopping_app
description: A new Flutter project

# The following line prevents the package from being accidentally published to pub.dev using `pub publish`.
publish_to: 'none'

# The following defines the environment for the current package.
environment:
  sdk: '^3.4.0'

# Dependencies specify other packages that your package needs in order to work.
dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.1
  mobx: ^2.0.0
  flutter_mobx: ^2.0.0
  hive: ^2.0.0
  hive_flutter: ^1.1.0
  isar: ^3.1.0+1
  json_annotation: ^4.0.1
  freezed_annotation: ^2.0.0
  provider: ^6.0.0
  badges: ^3.1.2

dev_dependencies:
  build_runner: ^2.0.0
  freezed: ^2.0.0
  flutter_lints: ^4.0.0
  hive_generator: ^2.0.0
  json_serializable: 6.8.0
  mobx_codegen: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
